### ISSUE TITLE
feature request: `*craft` preset

### ISSUE THREAD

**Issue by lucabello** [jnsgruk/concierge#27]
## Problem

Currently, when we pack charms in CI, we setup the environment with:

```yaml
- name: Setup LXD
  uses: canonical/setup-lxd@main
- name: Install charmcraft
  run: sudo snap install charmcraft --classic
```

I'd love to have a *concierge* preset for packing charms, that:
1. sets up `lxd` without bootstrapping it;
2. installs `charmcraft`.

Currently, I could use the `microk8s` preset, but installing `microk8s` is unnecessary and slows things down by approximately 5 minutes every time.

## Solutions

I have two ideas:
- have a `charmcraft` preset that does what I wrote above;
- have a `craft` preset that also installs the `snapcraft` and `rockcraft` snaps, following what's already done in the `microk8s` preset, but without `juju` and `microk8s`.

I can open a PR for this after I hear your thoughts; what do you think?

**Comment by jnsgruk** [comment]
Hmm, interesting. I think you could get most of what you're suggesting with a config file like so:

```yaml
providers:
  lxd:
    enable: true
    bootstrap: false

host:
  snaps:
    charmcraft:
      channel: latest/stable
```

The only overhead here (I think) is that the Juju snap would be installed
