### ISSUE TITLE
Add --dry-run option for prepare and restore

### ISSUE THREAD

**Issue by sed-i** [jnsgruk/concierge#61]
The one disadvantage of using concierge is that it hides know-how behind an opaque binary or behind a less-than-bash readable go code.
I was wondering if you'd consider capturing the shell commands in a yaml/go-template/etc of some kind?

I don't know much go at all, but from [juju.go](https://github.com/canonical/concierge/blob/main/internal/juju/juju.go) it seems like:

- Recipe components are broken down to (fallible) `func`s.
- A recipe (preset?) is made up of a subset of `func`s,
- The entire recipe is not known at compile time, as parts of it are constructed at runtime.

Without much thinking, the steps taken by concierge could perhaps be coded in something like:

```yaml
# juju.yaml.j2
steps:
  bootstrap:
    - command: juju bootstrap {{ controller_name }}
      success: Successfully bootstrapped {{controller_name}}: {{ _stdout }}  # "_stdout" is a special variable
      failure: Error bootstrapping {{ controller_name }}: {{ _err }}  # "_err" is a special variable

presets:
  charm-dev:
    - mode: parallel
      steps:
      - bootstrap
      - ...
```

But several existing abstraction for addressing a similar need come to mind:

- Github workflows (example: [setup-lxd](https://github.com/canonical/setup-lxd/blob/main/action.yml))
- Spread tests (example: [install juju+lxd+microk8s](https://github.com/canonical/charmcraft/blob/eec7648d55ab9e03ecf83d306f3d8440a686ae30/spread.yaml#L175))
- Justfile recipes (example: [install microceph](https://github.com/sed-i/reusable-justfiles/blob/29c123d0a5b60920c7cf32fd7ef9f49f25e19c25/charm-dev/ubuntu-24.04.just#L156))
- cloud-init and multipass blueprints (example: [charm-dev](https://github.com/canonical/multipass-blueprints/blob/main/v1/charm-dev.yaml))

I imagine that the highest convenience would come from composing 

1. cloud-init script,
2. installs a snap,
3. with ready-made recipes,
4. which are as close as possible to shell scripts.

With concierge we currently have 1+2+3, and only 4 is missing :)
