### ISSUE TITLE
feature request: add CONCIERGE_EXTRA_PIPS to concierge

### ISSUE THREAD

**Issue by taurus-forever** [jnsgruk/concierge#67]
Hi,

[Data team uses CONCIERGE_EXTRA_ variables](https://github.com/canonical/postgresql-operator/blob/5c1976477c6ffbd6a06a6576b70a68aae5aef8ab/spread.yaml#L42-L44) for CI tests:
```
    environment:
      CONCIERGE_EXTRA_SNAPS: charmcraft
      CONCIERGE_EXTRA_DEBS: pipx
```
The pipx is being used to install tox, poetry, charmcraftcache (manually: [#1](https://github.com/canonical/postgresql-operator/blob/5c1976477c6ffbd6a06a6576b70a68aae5aef8ab/spread.yaml#L51), [#2](https://github.com/canonical/postgresql-operator/blob/5c1976477c6ffbd6a06a6576b70a68aae5aef8ab/spread.yaml#L124)).
It would be great to introduce CONCIERGE_EXTRA_PIPS to simply do:
```
    environment:
      CONCIERGE_EXTRA_SNAPS: charmcraft
      CONCIERGE_EXTRA_DEBS: pipx
      CONCIERGE_EXTRA_PIPS: tox poetry charmcraftcache
```

Tnx!

P.S. can of worms: how to guaranty pipx installation before tox?
